[package]
name = "cpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
dotenv = "0.15.0"
toml = "0.8.8"
jrutils = {git = "https://github.com/jaypyles/jrutils"}

